language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t daopesdin/docker-test-react -f Dockerfile.dev .

script:
  - docker run -e CI=true daopesdin/docker-test-react npm run test
